import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {CartProvider} from "@/context/CartContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Panacea",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable}  antialiased  px-4 bg-gradient-to-br from-white via-white to-rose-50/50`}
        >
        <CartProvider>
            {children}
        </CartProvider>
        </body>
        </html>
    );
}
